definitions:
  models.CreateTaskRequest:
    properties:
      title:
        type: string
    required:
    - title
    type: object
  models.LoginRequest:
    properties:
      username:
        type: string
    required:
    - username
    type: object
  models.LoginResponse:
    properties:
      token:
        type: string
    type: object
  models.TaskResponse:
    properties:
      completed:
        type: boolean
      id:
        type: integer
      owner:
        type: string
      title:
        type: string
    type: object
  models.UpdateTaskRequest:
    properties:
      completed:
        type: boolean
      title:
        type: string
    required:
    - title
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para autenticación y gestión de tareas.
  title: API de Tareas Guarapo
  version: "1.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Autentica un usuario y retorna un token
      parameters:
      - description: Credenciales de login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login de usuario
      tags:
      - auth
  /api/tasks:
    get:
      description: Obtiene todas las tareas del usuario autenticado
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TaskResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Listar tareas
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Crea una nueva tarea para el usuario autenticado
      parameters:
      - description: Datos de la tarea
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.TaskResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Crear tarea
      tags:
      - tasks
  /api/tasks/{id}:
    delete:
      description: Elimina una tarea del usuario autenticado
      parameters:
      - description: ID de la tarea
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Eliminar tarea
      tags:
      - tasks
    get:
      description: Obtiene una tarea específica del usuario autenticado
      parameters:
      - description: ID de la tarea
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TaskResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Obtener tarea
      tags:
      - tasks
    put:
      consumes:
      - application/json
      description: Actualiza una tarea existente del usuario autenticado
      parameters:
      - description: ID de la tarea
        in: path
        name: id
        required: true
        type: integer
      - description: Datos de la tarea
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TaskResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Actualizar tarea
      tags:
      - tasks
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
