version: '3.8'
services:
  prueba_tecnica_go_guarapo:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: prueba-guarapo-go
    ports:
      - "8080:8080"